name: d3rm_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.25.2
  - tqdm
  - termcolor
  - mido=1.2
  - librosa=0.9.2
  - pytorch=2.1.2  # CPU-compatible
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pip:
      - wandb
      - adabelief-pytorch
      - nnaudio==0.3.2
      - mir_eval==0.7
      - timm
      - lightning
